# --------------- SERVER CONFIGS ---------------
server:
  servlet:
    context-path: /api-v1
  port: 8989

# --------------- SPRING BOOT CONFIGS ---------------
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pharmacy_dev?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        database: MySQL
        dialect: org.hibernate.dialect.MySQL5Dialect
        type: DEBUG